server:
  port: 8080
spring:
  application:
    name: "noreactivo--coverage&#61;jacoco"
  devtools:
    add-properties: false
#  h2:
#    console:
#      enabled: true
#      path: "/h2"
  profiles:
    include: null
  datasource:
    url: "jdbc:mysql://localhost:3306/arquitectura"
    username: "root"
    password: "root"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
#    driverClassName: "org.h2.Driver"
    jpa:
      database: mysql
      show-sql: true
      generate-ddl: true
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect


management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG # for queries
    io.r2dbc.postgresql.PARAM: DEBUG # for parameters
    org.springframework.r2dbc: DEBUG